CREATE TABLE museum_item_sets
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE museum_funds
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL
);


CREATE TABLE persons
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  text NOT NULL,
    second_name text NOT NULL,
    middle_name text NOT NULL
);

CREATE TABLE museum_items
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_number text not null UNIQUE,
    name             text NOT NULL UNIQUE,
    keeper_id        int  NOT NULL REFERENCES persons (id),
    set_id           int  NOT NULL REFERENCES museum_item_sets (id),
    fund_id          int  NOT NULL REFERENCES museum_funds (id),
    creation_date    timestamp,
    annotation       text
);

CREATE TABLE museum_item_movements
(
    id                    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accept_date           timestamp,
    exhibit_transfer_date timestamp,
    exhibit_return_date   timestamp,
    item_id               int NOT NULL REFERENCES museum_items (id),
    responsible_person_id int NOT NULL REFERENCES persons (id)
);
